# Generated by vscode-sync-extensions — do not edit by hand.
# Run vscode-sync-extensions to refresh from the live install, then
# rebuild. Install freely from the Marketplace UI, then snapshot here.
# IDs unavailable on this platform are skipped at build time (they keep
# working as manual installs via mutableExtensionsDir).
[
  "arturock.gitstash"
  "eamodio.gitlens"
  "editorconfig.editorconfig"
  "graphql.vscode-graphql-syntax"
  "jnoortheen.nix-ide"
  "mkhl.direnv"
  "orta.vscode-twoslash-queries"
  "oxc.oxc-vscode"
  "raillyhugo.one-hunter"
]
