{
  mkUserModule,
  forPlatform,
  pkgs,
  lib,
  ...
}:
let
  configDir = forPlatform {
    darwin = "Library/Application Support/Code/User";
    linux = ".config/Code/User";
  };

  # Full VS Code Marketplace exposed as Nix packages via the
  # nix-vscode-extensions overlay (wired in lib/mkDarwinHost.nix).
  marketplace = pkgs.vscode-marketplace;

  # Resolve a "publisher.name" extension ID to its Marketplace package.
  # Some extensions are removed/unavailable on this platform (e.g. licensing);
  # those throw on eval, so we tryEval and drop them — they keep working as
  # manual installs thanks to mutableExtensionsDir below.
  resolve =
    id:
    let
      parts = lib.splitString "." id;
      publisher = builtins.head parts;
      name = lib.concatStringsSep "." (builtins.tail parts);
      attempt = builtins.tryEval (
        let
          pkg = marketplace.${publisher}.${name};
        in
        builtins.seq (pkg.type or null) pkg
      );
    in
    if attempt.success then attempt.value else null;

  # Extensions whose marketplace package fails to *build* on this platform —
  # tryEval below only catches eval-time failures. They keep working as
  # manual installs via mutableExtensionsDir.
  # ponytail: hardcoded skip list; generalize only if it grows.
  brokenOnThisPlatform = forPlatform {
    # oxc resolves to an ancient 0.0.2 vsix on linux whose package.json
    # trips the extension builder ("cannot use null as iterable").
    linux = [ "oxc.oxc-vscode" ];
  };
  declaredIds = lib.subtractLists brokenOnThisPlatform (import ./extensions.nix);
  resolvedExtensions = builtins.filter (pkg: pkg != null) (map resolve declaredIds);
  unavailableIds = builtins.filter (id: resolve id == null) declaredIds;
  extensions =
    lib.warnIf (unavailableIds != [ ])
      "vscode: skipping extensions unavailable on this system (still installable manually): ${lib.concatStringsSep ", " unavailableIds}"
      resolvedExtensions;

  # Snapshot whatever is currently installed (declared + manually added from
  # the Marketplace UI) back into extensions.nix, so the Nix list matches
  # reality. This is the "save the current state to Nix" half of the
  # install-and-forget workflow: install freely in the UI, then run this and
  # rebuild to make it reproducible.
  syncExtensions = pkgs.writeShellScriptBin "vscode-sync-extensions" ''
    set -euo pipefail

    repo="''${VSCODE_NIX_REPO:-$HOME/nix-config}"
    out="$repo/modules/editor/vscode/extensions.nix"

    code_bin="$(command -v code || true)"
    if [ -z "$code_bin" ]; then
      code_bin="/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
    fi
    if [ ! -x "$code_bin" ]; then
      echo "vscode-sync-extensions: could not find the 'code' CLI" >&2
      exit 1
    fi

    tmp="$(mktemp)"
    {
      echo "# Generated by vscode-sync-extensions — do not edit by hand."
      echo "# Run vscode-sync-extensions to refresh from the live install, then"
      echo "# rebuild. Install freely from the Marketplace UI, then snapshot here."
      echo "# IDs unavailable on this platform are skipped at build time (they keep"
      echo "# working as manual installs via mutableExtensionsDir)."
      echo "["
      "$code_bin" --list-extensions | sort -u | while IFS= read -r ext; do
        [ -z "$ext" ] && continue
        printf '  "%s"\n' "$ext"
      done
      echo "]"
    } > "$tmp"

    ${pkgs.nixfmt-rfc-style}/bin/nixfmt "$tmp" >/dev/null 2>&1 || true
    mv "$tmp" "$out"

    echo "vscode-sync-extensions: wrote $out"
    echo "Next: sudo darwin-rebuild switch --flake $repo#vega"
  '';
in
mkUserModule {
  name = "vscode";

  # The editor itself comes from nixpkgs (via programs.vscode below) so that
  # extensions can be managed declaratively — there is no Homebrew cask.
  home =
    _:
    # Nested function so we get home-manager's `config` (needed for
    # mkOutOfStoreSymlink), which mkUserModule's home builder doesn't pass.
    { config, ... }:
    {
      # `vscode-sync-extensions`: snapshot the live extension set into Nix.
      home.packages = [ syncExtensions ];

      programs.vscode = {
        enable = true;
        package = pkgs.vscode;

        # Keep the extensions dir writable so the declared list coexists with
        # extensions installed manually from the Marketplace later. Run
        # `vscode-sync-extensions` to promote those manual installs into Nix.
        mutableExtensionsDir = true;

        # Declared set lives in extensions.nix (plain IDs), regenerated by the
        # sync script and resolved/filtered above.
        profiles.default.extensions = extensions;
      };

      # Settings are nix-first but live-writable: this points VS Code's
      # settings.json at the repo file via an out-of-store symlink, so edits in
      # the UI write straight back to the repo (and survive rebuilds). Assumes
      # the flake lives at ~/nix-config.
      home.file."${configDir}/settings.json".source =
        config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/nix-config/modules/editor/vscode/settings.json";
    };
}
